[package]
name = "publisher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crosstown_bus = "0.6.0"
borsh = "0.9.3"
borsh-derive = "0.9.1"
